#!/bin/bash

export EMAILER_HOME=$(cd "$(dirname $0)/.."; pwd)

MEMORY=${SBT_MEM:-5g}

java -Xmx${MEMORY} -Xms${MEMORY} -XX:MaxInlineSize=100 -XX:FreqInlineSize=100 -XX:MaxPermSize=150m \
  -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC $EXTRA_ARGS -jar $EMAILER_HOME/sbt/sbt-launch-*.jar "$@"
